Нужно больше функций
htmlacademy-javascript/1422099-keksobooking-22 pull request #2
Opened 2021-02-01 10:04 UTC by msuhaka

2021-02-01 21:18 UTC, raccoonroman requested changes

2021-02-01 21:18 UTC, raccoonroman commented on index.html
> +  <script src="js/main.js" defer></script>
это вам на лекции говорили так сделать? По сути атрибут defer здесь не нужен

2021-02-01 21:18 UTC, raccoonroman commented on js/main.js
> +  let rand = min - 0.5 + Math.random() * (max - min + 1);
если переменная не меняется, используй const

2021-02-01 21:18 UTC, raccoonroman commented on js/main.js
> +  return Math.round(rand.toFixed());
здесь возвращается строка, а правильно будет возвращать число

2021-02-01 21:18 UTC, raccoonroman commented on js/main.js
> +const getRandomInteger = function (min, max) {
вторая функция по заданию так же должна принимать третий параметр - 'количество_знаков_после_запятой'

2021-02-03 20:15 UTC, msuhaka commented on index.html
> +  <script src="js/main.js" defer></script>
Убрал. Исправлено

2021-02-03 20:18 UTC, msuhaka commented on js/main.js
> +const getRandomNumber = function (min, max) {
Исправлено.

2021-02-03 20:19 UTC, msuhaka commented on js/main.js
> +  let rand = min - 0.5 + Math.random() * (max - min + 1);
исправлено

2021-02-03 20:46 UTC, msuhaka commented on js/main.js
> +const getRandomInteger = function (min, max) {
исправлено

2021-02-03 21:29 UTC, raccoonroman requested changes

2021-02-03 21:29 UTC, raccoonroman commented on js/main.js
> +  return Math.round(rand.toFixed(decimalPlaces));
функция возвращает целое число, а должна возвращать число с указанным кол-вом знаков после точки.

2021-02-03 22:44 UTC, msuhaka commented on js/main.js
> +  return Math.round(rand.toFixed(decimalPlaces));
исправлено

2021-02-04 21:35 UTC, raccoonroman approved these changes

2021-02-04 21:36 UTC, raccoonroman commented
С почином!

2021-02-04 21:36 UTC, merged